name: Test Backend

on:
  workflow_run:
    workflows: ["Test Backend"]
    branches:
      - main
    types:
      - completed

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-24.04

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./simpleapi
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-backend:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push database
        uses: docker/build-push-action@v6
        with:
          context: ./BDD
          file: ./BDD/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devopps-database:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push httpd
        uses: docker/build-push-action@v6
        with:
          context: ./HTTP
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devopps-httpd:latest
          push: ${{ github.ref == 'refs/heads/main' }}




