name: CI devops 2025

on:
  push:
    branches: 
      - main
      - develop
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-24.04
    steps:
      # Checkout your GitHub code
      - uses: actions/checkout@v4

      # Setup JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # Build and test with Maven
      - name: Build and test with Maven
        run: mvn clean verify --file simpleapi/pom.xml
        
  quality-gate:
    needs: test-backend

    runs-on: ubuntu-24.04
    steps:
      - name: SonarCloud Quality Gate Check
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=devop2216_devop -Dsonar.organization=devop2216 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }} --file simpleapi/pom.xml


  # define job to build and publish docker image
  build-and-push-docker-image:
    needs: quality-gate
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-24.04

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./simpleapi
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-backend:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push database
        uses: docker/build-push-action@v6
        with:
          context: ./BDD
          file: ./BDD/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devopps-database:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push httpd
        uses: docker/build-push-action@v6
        with:
          context: ./HTTP
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devopps-httpd:latest
          push: ${{ github.ref == 'refs/heads/main' }}



