name: CI devops 2025

on:
  push:
    branches: 
      - main
      - develop
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-24.04
    steps:
      # Checkout your GitHub code
      - uses: actions/checkout@v4

      # Setup JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # Build and test with Maven
      - name: Build and test with Maven
        run: mvn clean verify --file simpleapi/pom.xml

build-and-push-docker-image:
  needs: test-backend
  runs-on: ubuntu-24.04

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build image and push backend
      uses: docker/build-push-action@v6
      with:
        context: ./simpleapi
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest

    - name: Build image and push database
      uses: docker/build-push-action@v6
      with:
        context: ./BDD
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest

    - name: Build image and push httpd
      uses: docker/build-push-action@v6
      with:
        context: ./HTTP
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest

